class CustomCitiesList {
  String cityName;
  String provinceName;
  String countryName;
  String longitude;
  String latitude;
  CustomCitiesList(
      {required this.cityName,
      required this.provinceName,
      required this.countryName,
      required this.latitude,
      required this.longitude});
}

class CustomProvinceNameList {
  String provinceName;
  String countryName;

  CustomProvinceNameList({required this.provinceName, required this.countryName});
}

List<CustomCitiesList> citiesList = [
  CustomCitiesList(
      cityName: "Abreus",
      provinceName: "Cienfuegos",
      countryName: "Cuba",
      latitude: " 22.2806",
      longitude: "-80.5678"),
  CustomCitiesList(
      cityName: "Agramonte",
      provinceName: "Matanzas",
      countryName: "Cuba",
      latitude: "22.6761",
      longitude: "-81.1156"),
  CustomCitiesList(
      cityName: "Aguada de Pasajeros",
      provinceName: "Cienfuegos",
      countryName: "Cuba",
      latitude: "22.3847",
      longitude: "-80.8461"),
  CustomCitiesList(
      cityName: "Alquízar",
      provinceName: "Artemisa",
      countryName: "Cuba",
      latitude: " 22.8067",
      longitude: " -82.5828"),
  CustomCitiesList(
      cityName: "Amancio",
      provinceName: "Las Tunas",
      countryName: "Cuba",
      latitude: "20.8197",
      longitude: "-77.5844"),
  CustomCitiesList(
      cityName: "Antilla",
      provinceName: "Holguín",
      countryName: "Cuba",
      latitude: "20.8411",
      longitude: "-75.7206"),
  CustomCitiesList(
      cityName: "Arroyo Naranjo",
      provinceName: "La Habana",
      countryName: "Cuba",
      latitude: "23.0436",
      longitude: "-82.3328"),
  CustomCitiesList(
      cityName: "Artemisa",
      provinceName: "Artemisa",
      countryName: "Cuba",
      latitude: "22.8136",
      longitude: "-82.7633"),
  CustomCitiesList(
      cityName: "Australia",
      provinceName: "Matanzas",
      countryName: "Cuba",
      latitude: "22.4995",
      longitude: "-81.1359"),
  CustomCitiesList(
      cityName: "Báguanos",
      provinceName: "Holguín",
      countryName: "Cuba",
      latitude: "20.7631",
      longitude: "-76.0297"),
  CustomCitiesList(
      cityName: "Bahía Honda",
      provinceName: "Artemisa",
      countryName: "Cuba",
      latitude: "22.9064",
      longitude: "-83.1639"),
  CustomCitiesList(
    cityName: "Banes",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "20.9697",
    longitude: "-75.7117",
  ),
  CustomCitiesList(
    cityName: "Baracoa",
    provinceName: "Guantánamo",
    countryName: "Cuba",
    latitude: "20.3486",
    longitude: "-74.5106",
  ),
  CustomCitiesList(
    cityName: "Baraguá",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: "21.6819",
    longitude: "-78.6244",
  ),
  CustomCitiesList(
    cityName: "Bartolomé Masó",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.1686",
    longitude: "-76.9428",
  ),
  CustomCitiesList(
    cityName: "Batabanó",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "22.7167",
    longitude: "-82.2833",
  ),
  CustomCitiesList(
    cityName: "Bauta",
    provinceName: "Artemisa",
    countryName: "Cuba",
    latitude: " 22.9919",
    longitude: "-82.5492",
  ),
  CustomCitiesList(
    cityName: "Bayamo",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.3817",
    longitude: "-76.6428",
  ),
  CustomCitiesList(
    cityName: "Bejucal",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "22.9328",
    longitude: "-82.3869",
  ),
  CustomCitiesList(
    cityName: "Bolivia",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: "22.075",
    longitude: "-78.3503",
  ),
  CustomCitiesList(
    cityName: "Buey Arriba",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.1736",
    longitude: "-76.7494",
  ),
  CustomCitiesList(
    cityName: "Cabaiguán",
    provinceName: "Sancti Spíritus",
    countryName: "Cuba",
    latitude: "22.0839",
    longitude: "-79.4953",
  ),
  CustomCitiesList(
    cityName: "Cacocum",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "20.7439",
    longitude: "-76.3242",
  ),
  CustomCitiesList(
    cityName: "Caibarién",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.5158",
    longitude: "-79.4722",
  ),
  CustomCitiesList(
    cityName: "Caimanera",
    provinceName: "Guantánamo",
    countryName: "Cuba",
    latitude: "19.9947",
    longitude: "-75.16",
  ),
  CustomCitiesList(
    cityName: "Caimito",
    provinceName: "Artemisa",
    countryName: "Cuba",
    latitude: "22.9575",
    longitude: "-82.5964",
  ),
  CustomCitiesList(
    cityName: "Calimete",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "22.5339 -80.9097",
    longitude: "",
  ),
  CustomCitiesList(
    cityName: "Camagüey",
    provinceName: "Camagüey ",
    countryName: "Cuba",
    latitude: "21.3839",
    longitude: "-77.9075",
  ),
  CustomCitiesList(
    cityName: "Camajuaní",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.4678",
    longitude: "-79.7239",
  ),
  CustomCitiesList(
    cityName: "Campechuela",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.2333",
    longitude: "-77.2792",
  ),
  CustomCitiesList(
    cityName: "Candelaria",
    provinceName: "Artemisa",
    countryName: "Cuba",
    latitude: "22.7439",
    longitude: "-82.9581",
  ),
  CustomCitiesList(
    cityName: "Cárdenas",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "23.0428",
    longitude: "81.2036",
  ),
  CustomCitiesList(
    cityName: "Carlos Manuel de Céspedes",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "21.5767",
    longitude: "-78.2775",
  ),
  CustomCitiesList(
    cityName: "Cauto Cristo",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.5619",
    longitude: "-76.4694",
  ),
  CustomCitiesList(
    cityName: "Cayo Mambí",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "20.6647",
    longitude: "-75.2814",
  ),
  CustomCitiesList(
    cityName: "Centro Haba",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "23.1333",
    longitude: "-82.3833",
  ),
  CustomCitiesList(
    cityName: "Chambas",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: "22.1967",
    longitude: "-78.9133",
  ),
  CustomCitiesList(
    cityName: "Ciego de Ávila",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: "21.8481",
    longitude: "-78.7631",
  ),
  CustomCitiesList(
    cityName: "Cienfuegos",
    provinceName: "Cienfuegos",
    countryName: "Cuba",
    latitude: "22.1456",
    longitude: "-80.4364",
  ),
  CustomCitiesList(
    cityName: "Cifuentes",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.6208",
    longitude: "-80.0661",
  ),
  CustomCitiesList(
    cityName: "Ciro Redondo",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: "22.0189",
    longitude: "-78.7031",
  ),
  CustomCitiesList(
    cityName: "Colombia",
    provinceName: "Las Tunas",
    countryName: "Cuba",
    latitude: "20.9906",
    longitude: "-77.4158",
  ),
  CustomCitiesList(
    cityName: "Colón",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "22.7225",
    longitude: "-80.9067",
  ),
  CustomCitiesList(
    cityName: "Consolación del Sur",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.5083",
    longitude: "-83.5172",
  ),
  CustomCitiesList(
    cityName: "Contramaestre",
    provinceName: "Santiago de Cuba",
    countryName: "Cuba",
    latitude: "20.3",
    longitude: "-76.2506",
  ),
  CustomCitiesList(
    cityName: "Corralillo",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.9856",
    longitude: "-80.5831",
  ),
  CustomCitiesList(
    cityName: "Cruces",
    provinceName: "Cienfuegos",
    countryName: "Cuba",
    latitude: "22.3419",
    longitude: "-80.2761",
  ),
  CustomCitiesList(
    cityName: "Cueto",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "20.6481",
    longitude: "-75.9317",
  ),
  CustomCitiesList(
    cityName: "Cumanayagua",
    provinceName: "Cienfuegos",
    countryName: "Cuba",
    latitude: "22.1522",
    longitude: "-80.2011",
  ),
  CustomCitiesList(
    cityName: "Encrucijada",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.6169",
    longitude: "-79.8661",
  ),
  CustomCitiesList(
    cityName: "Esmeralda",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "21.8561",
    longitude: "-78.1114",
  ),
  CustomCitiesList(
    cityName: "Esperanza",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.4472",
    longitude: "-80.0966",
  ),
  CustomCitiesList(
    cityName: "Falla",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: "22.1704",
    longitude: "-78.7872",
  ),
  CustomCitiesList(
    cityName: "Florencia",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: " 22.1475",
    longitude: " -78.9669",
  ),
  CustomCitiesList(
    cityName: "Florida",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "21.5294",
    longitude: "-78.2228",
  ),
  CustomCitiesList(
    cityName: "Fomento",
    provinceName: "Sancti Spíritus",
    countryName: "Cuba",
    latitude: "22.1053",
    longitude: "-79.7203",
  ),
  CustomCitiesList(
    cityName: "Gibara",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "21.1072",
    longitude: "-76.1367",
  ),
  CustomCitiesList(
    cityName: "Guáimaro",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "21.0589",
    longitude: "-77.3478",
  ),
  CustomCitiesList(
    cityName: "Guamá Abajo",
    provinceName: "Santiago de Cuba",
    countryName: "Cuba",
    latitude: "19.9758",
    longitude: "-76.41",
  ),
  CustomCitiesList(
    cityName: "Centro Habana",
    provinceName: "La Habana",
    countryName: "Cuba",
    latitude: "23.1252",
    longitude: "-82.3007",
  ),
  CustomCitiesList(
    cityName: "Guanabacoa",
    provinceName: "La Habana",
    countryName: "Cuba",
    latitude: "23.1252",
    longitude: "-82.3007",
  ),
  CustomCitiesList(
    cityName: "Guanajay",
    provinceName: "Artemisa",
    countryName: "Cuba",
    latitude: "22.9306",
    longitude: "-82.6881",
  ),
  CustomCitiesList(
    cityName: "Guane",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.2006",
    longitude: "-84.0839",
  ),
  CustomCitiesList(
    cityName: "Guantánamo",
    provinceName: "Guantánamo",
    countryName: "Cuba",
    latitude: "20.1367",
    longitude: "-75.2139",
  ),
  CustomCitiesList(
    cityName: "Guayos",
    provinceName: "Sancti Spíritus",
    countryName: "Cuba",
    latitude: "22.0497",
    longitude: "-79.4622",
  ),
  CustomCitiesList(
    cityName: "Güines",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "22.8475",
    longitude: "-82.0236",
  ),
  CustomCitiesList(
    cityName: "Güira de Melena",
    provinceName: "Artemisa",
    countryName: "Cuba",
    latitude: "22.8019",
    longitude: "-82.5047",
  ),
  CustomCitiesList(
    cityName: "Guisa",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.2608",
    longitude: "-76.5381",
  ),
  CustomCitiesList(
    cityName: "Havana",
    provinceName: "La Habana",
    countryName: "Cuba",
    latitude: "23.1367",
    longitude: "-82.3589",
  ),
  CustomCitiesList(
    cityName: "Holguín",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "20.8869",
    longitude: "-76.2592",
  ),
  CustomCitiesList(
    cityName: "Imías",
    provinceName: "Guantánamo",
    countryName: "Cuba",
    latitude: "20.0767",
    longitude: "-74.6519",
  ),
  CustomCitiesList(
    cityName: "Jagüey Grande",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "22.5292",
    longitude: "-81.1325",
  ),
  CustomCitiesList(
    cityName: "Jaruco",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "23.0428",
    longitude: "-82.0094",
  ),
  CustomCitiesList(
    cityName: "Jatibonico",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "21.9464",
    longitude: "-79.1675",
  ),
  CustomCitiesList(
    cityName: "Jesús Menéndez",
    provinceName: "Las Tunas",
    countryName: "Cuba",
    latitude: "21.1633",
    longitude: "-76.4775",
  ),
  CustomCitiesList(
    cityName: "Jiguaní",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.3731",
    longitude: "-76.4222",
  ),
  CustomCitiesList(
    cityName: "Jimaguayú",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "21.2667",
    longitude: "-77.8303",
  ),
  CustomCitiesList(
    cityName: "Jobabo",
    provinceName: "Las Tunas",
    countryName: "Cuba",
    latitude: "20.9078",
    longitude: "-77.2831",
  ),
  CustomCitiesList(
    cityName: "Jovellanos",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "22.8106",
    longitude: "-81.1981",
  ),
  CustomCitiesList(
    cityName: "La Palma",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.7472",
    longitude: "-83.5525",
  ),
  CustomCitiesList(
    cityName: "Jatibonico",
    provinceName: "Sancti Spíritus",
    countryName: "Cuba",
    latitude: "21.7606",
    longitude: "-79.2433",
  ),
  CustomCitiesList(
    cityName: "La Sierpe",
    provinceName: "Sancti Spíritus",
    countryName: "Cuba",
    latitude: "21.7606",
    longitude: "-79.2433",
  ),
  CustomCitiesList(
    cityName: "Lajas",
    provinceName: "Cienfuegos",
    countryName: "Cuba",
    latitude: "22.4164",
    longitude: "-80.2906",
  ),
  CustomCitiesList(
    cityName: "Las Tunas",
    provinceName: "Las Tunas",
    countryName: "Cuba",
    latitude: "20.9597",
    longitude: "-76.9544",
  ),
  CustomCitiesList(
    cityName: "Limonar",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "22.9561",
    longitude: "-81.4086",
  ),
  CustomCitiesList(
    cityName: "Los Arabos",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "22.74",
    longitude: "-80.7161",
  ),
  CustomCitiesList(
    cityName: "Los Palacios",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.5822",
    longitude: "-83.2489",
  ),
  CustomCitiesList(
    cityName: "Madruga",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "22.9164",
    longitude: "-81.8572",
  ),
  CustomCitiesList(
    cityName: "Majagua",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: "21.9244",
    longitude: "-78.9906",
  ),
  CustomCitiesList(
    cityName: "Majibacoa",
    provinceName: "Las Tunas ",
    countryName: "Cuba",
    latitude: "20.9172",
    longitude: "-76.8764",
  ),
  CustomCitiesList(
    cityName: "Manatí",
    provinceName: "Las Tunas",
    countryName: "Cuba",
    latitude: "21.3144",
    longitude: "-76.9378",
  ),
  CustomCitiesList(
    cityName: "Manicaragua",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.15",
    longitude: "-79.9764",
  ),
  CustomCitiesList(
    cityName: "Mantua",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.2908",
    longitude: "-84.2875",
  ),
  CustomCitiesList(
    cityName: "Manuel Tames",
    provinceName: "Guantánamo",
    countryName: "Cuba",
    latitude: "20.1803",
    longitude: "-75.0514",
  ),
  CustomCitiesList(
    cityName: "Manzanillo",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.3397",
    longitude: "-77.1086",
  ),
  CustomCitiesList(
    cityName: "Mariel",
    provinceName: "Artemisa",
    countryName: "Cuba",
    latitude: "22.9936",
    longitude: "-82.7539",
  ),
  CustomCitiesList(
    cityName: "Martí",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "22.9522",
    longitude: "-80.9167",
  ),
  CustomCitiesList(
    cityName: "Mataguá",
    provinceName: "Villa Clara ",
    countryName: "Cuba",
    latitude: "22.237",
    longitude: "-79.9992",
  ),
  CustomCitiesList(
    cityName: "Matanzas",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "23.0511",
    longitude: "-81.5753",
  ),
  CustomCitiesList(
    cityName: "Mayarí",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "20.6592",
    longitude: "-75.6781",
  ),
  CustomCitiesList(
    cityName: "Media Luna",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.1444",
    longitude: "-77.4361",
  ),
  CustomCitiesList(
    cityName: "Melena del Sur",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "22.7881",
    longitude: "-82.1512",
  ),
  CustomCitiesList(
    cityName: "Mella",
    provinceName: "Santiago de Cuba",
    countryName: "Cuba",
    latitude: "20.3694",
    longitude: "-75.9111",
  ),
  CustomCitiesList(
    cityName: "Minas",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "21.4894",
    longitude: "-77.605",
  ),
  CustomCitiesList(
    cityName: "Minas de Matahambre",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.5822",
    longitude: "-83.9492",
  ),
  CustomCitiesList(
    cityName: "Moa",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "20.6397",
    longitude: "-74.9175",
  ),
  CustomCitiesList(
    cityName: "Morón",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: "22.1108",
    longitude: "-78.6278",
  ),
  CustomCitiesList(
    cityName: "Najasa",
    provinceName: "Camagüey ",
    countryName: "Cuba",
    latitude: "21.0836",
    longitude: "-77.7472",
  ),
  CustomCitiesList(
    cityName: "Niquero",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.0472",
    longitude: "-77.5781",
  ),
  CustomCitiesList(
    cityName: "Nueva Gerona",
    provinceName: "Isla de la Juventud",
    countryName: "Cuba",
    latitude: "21.8847",
    longitude: "-82.8011",
  ),
  CustomCitiesList(
    cityName: "Nueva Paz",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "22.7633",
    longitude: "-81.7581",
  ),
  CustomCitiesList(
    cityName: "Nuevitas",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "21.5403",
    longitude: "-77.2644",
  ),
  CustomCitiesList(
    cityName: "Palma Soriano",
    provinceName: "Santiago de Cuba",
    countryName: "Cuba",
    latitude: "20.2139",
    longitude: "-75.9919",
  ),
  CustomCitiesList(
    cityName: "Palmira",
    provinceName: "Cienfuegos",
    countryName: "Cuba",
    latitude: "22.2444",
    longitude: "-80.3944",
  ),
  CustomCitiesList(
    cityName: "Perico",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "22.7753",
    longitude: "-81.0153",
  ),
  CustomCitiesList(
    cityName: "Pilón",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "19.9053",
    longitude: "-77.3208",
  ),
  CustomCitiesList(
    cityName: "Pinar del Río",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.4122",
    longitude: "-83.6719",
  ),
  CustomCitiesList(
    cityName: "Placetas",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.3158",
    longitude: "-79.6556",
  ),
  CustomCitiesList(
    cityName: "Primero de Enero",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: "21.9453",
    longitude: "-78.4189",
  ),
  CustomCitiesList(
    cityName: "Puerto Padre",
    provinceName: "Las Tunas",
    countryName: "Cuba",
    latitude: "21.195",
    longitude: "-76.6017",
  ),
  CustomCitiesList(
    cityName: "Quemado de Güines",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.79",
    longitude: "-80.2561",
  ),
  CustomCitiesList(
    cityName: "Quivicán",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "22.8247",
    longitude: "-82.3558",
  ),
  CustomCitiesList(
    cityName: "Ranchuelo",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.3764",
    longitude: "-80.151",
  ),
  CustomCitiesList(
    cityName: "Remedios",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.4922",
    longitude: "-79.5458",
  ),
  CustomCitiesList(
    cityName: "Río Cauto",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.5636",
    longitude: "-76.9172",
  ),
  CustomCitiesList(
    cityName: "Rodas",
    provinceName: "Cienfuegos",
    countryName: "Cuba",
    latitude: "22.3428",
    longitude: "-80.5553",
  ),
  CustomCitiesList(
    cityName: "Sagua de Tánamo",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "20.5858",
    longitude: "-75.2417",
  ),
  CustomCitiesList(
    cityName: "Sagua la Grande",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.8086",
    longitude: "-80.0711",
  ),
  CustomCitiesList(
    cityName: "Salvador",
    provinceName: "Guantánamo",
    countryName: "Cuba",
    latitude: "20.2094",
    longitude: "-75.2231",
  ),
  CustomCitiesList(
    cityName: "San Antonio de las Vueltas",
    provinceName: "Villa Clara ",
    countryName: "Cuba",
    latitude: "22.5167",
    longitude: "-79.7021",
  ),
  CustomCitiesList(
    cityName: "San Antonio de los Baños",
    provinceName: "Artemisa",
    countryName: "Cuba",
    latitude: "22.8889",
    longitude: "-82.4989",
  ),
  CustomCitiesList(
    cityName: "San Antonio del Sur",
    provinceName: "Guantánamo",
    countryName: "Cuba",
    latitude: "20.0569",
    longitude: "-74.8078",
  ),
  CustomCitiesList(
    cityName: "San Cristóbal",
    provinceName: "Artemisa",
    countryName: "Cuba",
    latitude: "22.7169",
    longitude: "-83.0511",
  ),
  CustomCitiesList(
    cityName: "San Germán",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "20.6011",
    longitude: "-76.1325",
  ),
  CustomCitiesList(
    cityName: "San José de las Lajas",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "22.9678",
    longitude: "-82.1558",
  ),
  CustomCitiesList(
    cityName: "San Juan y Martínez",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.2667",
    longitude: "-83.8333",
  ),
  CustomCitiesList(
    cityName: "San Luis",
    provinceName: "Santiago de Cuba",
    countryName: "Cuba",
    latitude: "20.1881",
    longitude: "-75.8486",
  ),
  CustomCitiesList(
    cityName: "San Luis",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.2828",
    longitude: "-83.7681",
  ),
  CustomCitiesList(
    cityName: "San Nicolás",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "22.7819",
    longitude: "-81.9069",
  ),
  CustomCitiesList(
    cityName: "Sancti Spíritus",
    provinceName: "Sancti Spíritus",
    countryName: "Cuba",
    latitude: "21.9339",
    longitude: "-79.4439",
  ),
  CustomCitiesList(
    cityName: "Sandino",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.0803",
    longitude: "-84.206",
  ),
  CustomCitiesList(
    cityName: "Santa Clara",
    provinceName: "Villa Clara admin",
    countryName: "Cuba",
    latitude: "22.4069",
    longitude: "-79.9649",
  ),
  CustomCitiesList(
    cityName: "Santa Cruz del Norte",
    provinceName: "Mayabeque",
    countryName: "Cuba",
    latitude: "23.1556",
    longitude: "-81.9267",
  ),
  CustomCitiesList(
    cityName: "Santa Cruz del Sur",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "20.7194",
    longitude: "-77.9911",
  ),
  CustomCitiesList(
    cityName: "Santa Lucía",
    provinceName: "Holguín",
    countryName: "Cuba",
    latitude: "21.0281",
    longitude: "-75.9964",
  ),
  CustomCitiesList(
    cityName: "Santiago de Cuba",
    provinceName: "Santiago de Cuba",
    countryName: "Cuba",
    latitude: "20.0217",
    longitude: "-75.8294",
  ),
  CustomCitiesList(
    cityName: "Santo Domingo",
    provinceName: "Villa Clara",
    countryName: "Cuba",
    latitude: "22.5833",
    longitude: "-80.2383",
  ),
  CustomCitiesList(
    cityName: "Sibanicú",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "21.2389",
    longitude: "-77.5211",
  ),
  CustomCitiesList(
    cityName: "Sola",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "21.6744",
    longitude: "-77.6806",
  ),
  CustomCitiesList(
    cityName: "Taguasco",
    provinceName: "Sancti Spíritus",
    countryName: "Cuba",
    latitude: "22.005",
    longitude: "-79.265",
  ),
  CustomCitiesList(
    cityName: "Trinidad",
    provinceName: "Sancti Spíritus ",
    countryName: "Cuba",
    latitude: "21.8042",
    longitude: "-79.9831",
  ),
  CustomCitiesList(
    cityName: "Unión de Reyes",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "22.8003",
    longitude: "-81.5372",
  ),
  CustomCitiesList(
    cityName: "Varadero",
    provinceName: "Matanzas",
    countryName: "Cuba",
    latitude: "23.1394",
    longitude: "-81.2861",
  ),
  CustomCitiesList(
    cityName: "Vázquez",
    provinceName: "Las Tunas",
    countryName: "Cuba",
    latitude: "21.1399",
    longitude: "-76.7294",
  ),
  CustomCitiesList(
    cityName: "Venezuela",
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
    latitude: "21.7511",
    longitude: "-78.7792",
  ),
  CustomCitiesList(
    cityName: "Vertientes",
    provinceName: "Camagüey",
    countryName: "Cuba",
    latitude: "21.2569",
    longitude: "-78.1492",
  ),
  CustomCitiesList(
    cityName: "Viñales",
    provinceName: "Pinar del Río",
    countryName: "Cuba",
    latitude: "22.6153",
    longitude: "-83.7158",
  ),
  CustomCitiesList(
    cityName: "Yaguajay",
    provinceName: "Sancti Spíritus",
    countryName: "Cuba",
    latitude: "22.3303",
    longitude: "-79.2369",
  ),
  CustomCitiesList(
    cityName: "Yara",
    provinceName: "Granma",
    countryName: "Cuba",
    latitude: "20.2767",
    longitude: "-76.9469",
  ),
];
List<CustomProvinceNameList> provinceName = [
  CustomProvinceNameList(
    provinceName: "Artemisa",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Camagüey",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Ciego de Ávila",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Cienfuegos",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Granma",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Guantánamo",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Holguín",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Isla de la Juventud",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "La Habana",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Las Tunas",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Matanzas",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Mayabeque",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Pinar del Río",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Santiago de Cuba",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Sancti Spíritus",
    countryName: "Cuba",
  ),
  CustomProvinceNameList(
    provinceName: "Villa Clara",
    countryName: "Cuba",
  ),
];
